'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public Property ArbitraryMaxSplits() As Integer
            Get
                Return CType(Me("ArbitraryMaxSplits"),Integer)
            End Get
            Set
                Me("ArbitraryMaxSplits") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property MP4PlaybackEnabled() As Boolean
            Get
                Return CType(Me("MP4PlaybackEnabled"),Boolean)
            End Get
            Set
                Me("MP4PlaybackEnabled") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property AzidNormalizeAudio() As Boolean
            Get
                Return CType(Me("AzidNormalizeAudio"),Boolean)
            End Get
            Set
                Me("AzidNormalizeAudio") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property SplitFiles() As Boolean
            Get
                Return CType(Me("SplitFiles"),Boolean)
            End Get
            Set
                Me("SplitFiles") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("4096")>  _
        Public Property SplitFileThreshold() As Integer
            Get
                Return CType(Me("SplitFileThreshold"),Integer)
            End Get
            Set
                Me("SplitFileThreshold") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("mp4")>  _
        Public Property OutputExtension() As String
            Get
                Return CType(Me("OutputExtension"),String)
            End Get
            Set
                Me("OutputExtension") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("english.xml")>  _
        Public Property i18n() As String
            Get
                Return CType(Me("i18n"),String)
            End Get
            Set
                Me("i18n") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DefaultOutputFolder() As String
            Get
                Return CType(Me("DefaultOutputFolder"),String)
            End Get
            Set
                Me("DefaultOutputFolder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CustomScratchFolder() As String
            Get
                Return CType(Me("CustomScratchFolder"),String)
            End Get
            Set
                Me("CustomScratchFolder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DeleteTempFiles() As Boolean
            Get
                Return CType(Me("DeleteTempFiles"),Boolean)
            End Get
            Set
                Me("DeleteTempFiles") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property AlwaysUseLanguage() As String
            Get
                Return CType(Me("AlwaysUseLanguage"),String)
            End Get
            Set
                Me("AlwaysUseLanguage") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property AutoPickTracks() As Boolean
            Get
                Return CType(Me("AutoPickTracks"),Boolean)
            End Get
            Set
                Me("AutoPickTracks") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property CutoffTimePrompt() As Boolean
            Get
                Return CType(Me("CutoffTimePrompt"),Boolean)
            End Get
            Set
                Me("CutoffTimePrompt") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("none")>  _
        Public Property AzidDRC() As String
            Get
                Return CType(Me("AzidDRC"),String)
            End Get
            Set
                Me("AzidDRC") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property AzidFilterRearChannels() As Boolean
            Get
                Return CType(Me("AzidFilterRearChannels"),Boolean)
            End Get
            Set
                Me("AzidFilterRearChannels") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property MoveOutputFile() As Boolean
            Get
                Return CType(Me("MoveOutputFile"),Boolean)
            End Get
            Set
                Me("MoveOutputFile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property AzidDialogNormalization() As Boolean
            Get
                Return CType(Me("AzidDialogNormalization"),Boolean)
            End Get
            Set
                Me("AzidDialogNormalization") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("dpl")>  _
        Public Property AzidStereoDownmix() As String
            Get
                Return CType(Me("AzidStereoDownmix"),String)
            End Get
            Set
                Me("AzidStereoDownmix") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property HaltOnIncompatible() As Boolean
            Get
                Return CType(Me("HaltOnIncompatible"),Boolean)
            End Get
            Set
                Me("HaltOnIncompatible") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property AllowUNCPathInput() As Boolean
            Get
                Return CType(Me("AllowUNCPathInput"),Boolean)
            End Get
            Set
                Me("AllowUNCPathInput") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property RoundPAR() As Boolean
            Get
                Return CType(Me("RoundPAR"),Boolean)
            End Get
            Set
                Me("RoundPAR") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\tools\mp4box\MP4Box_default.exe")>  _
        Public Property MP4BoxPath() As String
            Get
                Return CType(Me("MP4BoxPath"),String)
            End Get
            Set
                Me("MP4BoxPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property MP4BoxOutputDirect() As Boolean
            Get
                Return CType(Me("MP4BoxOutputDirect"),Boolean)
            End Get
            Set
                Me("MP4BoxOutputDirect") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property MKVExtractSync() As Boolean
            Get
                Return CType(Me("MKVExtractSync"),Boolean)
            End Get
            Set
                Me("MKVExtractSync") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ProvideCustomAR() As Boolean
            Get
                Return CType(Me("ProvideCustomAR"),Boolean)
            End Get
            Set
                Me("ProvideCustomAR") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-q")>  _
        Public Property NeroEncodeOption() As String
            Get
                Return CType(Me("NeroEncodeOption"),String)
            End Get
            Set
                Me("NeroEncodeOption") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.5")>  _
        Public Property NeroEncodeValue() As Single
            Get
                Return CType(Me("NeroEncodeValue"),Single)
            End Get
            Set
                Me("NeroEncodeValue") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property NeroForceNonSSE() As String
            Get
                Return CType(Me("NeroForceNonSSE"),String)
            End Get
            Set
                Me("NeroForceNonSSE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property OutputUpperCase() As Boolean
            Get
                Return CType(Me("OutputUpperCase"),Boolean)
            End Get
            Set
                Me("OutputUpperCase") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property MainUIWidth() As Integer
            Get
                Return CType(Me("MainUIWidth"),Integer)
            End Get
            Set
                Me("MainUIWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property MainUIHeight() As Integer
            Get
                Return CType(Me("MainUIHeight"),Integer)
            End Get
            Set
                Me("MainUIHeight") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property MainUIWindowState() As Integer
            Get
                Return CType(Me("MainUIWindowState"),Integer)
            End Get
            Set
                Me("MainUIWindowState") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-1")>  _
        Public Property MainUITop() As Integer
            Get
                Return CType(Me("MainUITop"),Integer)
            End Get
            Set
                Me("MainUITop") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-1")>  _
        Public Property MainUILeft() As Integer
            Get
                Return CType(Me("MainUILeft"),Integer)
            End Get
            Set
                Me("MainUILeft") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.XenonMKV.My.MySettings
            Get
                Return Global.XenonMKV.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
